### ISSUE TITLE
AppEngine integration

### ISSUE THREAD

**Issue by reinert** [tbroyer/gwt-maven-archetypes#31]
Have you ever tried to enable AppEngine integration? I could set-up it, but the only thing I couldn't is to add shared classpath to AppEngine devserver (in order to not require a restart after changing some shared class in dev mode). I googled about setting additional classpath entries to the appengine plugin but I couldn't find anything useful. AppEngine maven plugin seems to lack many features. Do you know anything about it?

**Comment by freddyboucher** [comment]
Hi @reinert 
I've just posted on Github a GWT demo project that uses App Engine and **tbroyer/gwt-maven-archetypes**. You would probably find it interested.
https://github.com/freddyboucher/gwt-storage-objectify

**Comment by reinert** [comment]
nice! thanks!
