### ISSUE TITLE
using modular-webapp archetype with super-dev-mode?

### ISSUE THREAD

**Issue by kaefert** [tbroyer/gwt-maven-archetypes#35]
Is it possible to use your modular-webapp archetype together with the super dev mode? 

When I run mvn gwt:codeserver on the root project, it starts a web server but doesn't contain the module, when I run it on the *-server subproject it wont start because:
Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer

**Comment by tbroyer** [comment]
What do you mean by “doesn't contain the module”?

Have you followed the instructions in the README? Following them to the letter (`mvn gwt:codeserver -pl *-client -am` in one console, `mvn tomcat7:run -pl *-server -am -Denv=dev` in another, and then opening `http://localhost:8080` in a browser) works like a charm for me.

**Comment by kaefert** [comment]
oh. hmm. nope sorry, I was somehow under the impression that the new dev mode was a single thing, and the run two separate things to run for debugging was only for the old normal dev mode.

sorry. will try what you suggested on monday when I'm back at my dev-machine.
