### ISSUE TITLE
Can't make this archetype work in my project without making a GWT module for shared

### ISSUE THREAD

**Issue by shauntarves** [tbroyer/gwt-maven-archetypes#37]
I have a project based on an older version of this archetype...back when it was still using the mojo version of the gwt-maven-plugin.

I have never been able to make my project work without creating a GWT module for the shared maven module. I always get the "No source can be found" error when trying to compile the client module.

I'm going back and trying to understand how does/should this work without a module for the shared code? I can't tell if it's because in the archetype, App, GreetingService, and GreetingServiceAsync classes all belong to the same "java" package so the App.java class doesn't have to declare imports for them. That's the only difference I can see between the archetype and my project. Either way, I'm stumped.

**Comment by tbroyer** [comment]
Yes, that's exactly the reason. GWT modules define subsets of the classpath based on package prefixes and path patterns, therefore you have to reason in terms of classpath/packages, not file paths.

If you just moved the shared code into a `shared` subpackage and the client code into a `client` subpackage, then you can just add

```xml
<source path="client" />
<source path="shared" />
```

into your module in `client`; no need to create a module for the shared code.
