### ISSUE TITLE
How to add Spring Boot to this GWT project?

### ISSUE THREAD

**Issue by pedy711** [tbroyer/gwt-maven-archetypes#47]
This plugin is very well defined, but I don't know how to handle the server side using Spring boot. I was wondering if you could point me to the right direction about how to add Spring boot to GWT application. I already checked some of the sources online, but no luck so far. With Mojo plugin I can set:

`<start-class>com.test.server.ServerMain</start-class>`

How is it done in your plugin?

Thank you in advance.

**Comment by tbroyer** [comment]
I have no idea how Spring Boot works; please ask for help on StackOverflow or the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit). Things shouldn't be much different though.

BTW, this is a repository about Maven archetypes, not the gwt-maven-plugin (see [here](https://github.com/tbroyer/gwt-maven-plugin))

**Comment by tbroyer** [comment]
Fwiw, I had a quick look at [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/maven-plugin/run-mojo.html) today (for other reasons), and it looks like you would "simply" have to use `<addResources>true</addResources>` and possibly configure some additional resource folders (`<folders>`). You'd run `mvn spring-boot:run` to start your webapp, and `mvn gwt:codeserver` (with a properly configured `<launcherDir>` pointing to a folder used/watched by `spring-boot:run`) to run GWT's CodeServer for dev mode.

If you need further help, please ask on StackOverflow or the GWT forum.
