### ISSUE TITLE
generated sources are not available to the gwt compiler

### ISSUE THREAD

**Issue by vegegoku** [tbroyer/gwt-maven-archetypes#48]
Hi
when creating an application from this archetype, then use an annotation processor to generate some code  the gwt compilation fails and complain that the source code for the generated classes does not exist, after some research i found that if the mvn-compiler-plugin is upgraded to 3.5.1 instead of 3.1 it will work

looking at this section of the pom file 
```
 <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <!-- Do not upgrade past 3.1 to avoid triggering https://issues.apache.org/jira/browse/MSOURCES-95 -->
          <version>3.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
```

you have a comment explains why you use `3.1` instead of `3.5.1`

here is another link about this issue
https://github.com/codehaus-plexus/plexus-archiver/issues/24

annotation processing is now being heavily used in gwt applications and is being recommended over deferred binding, so it might be better to make this archetype works with annotation processing out of the box, and have a comment for when `3.1` is required, or at least  comment with hint about upgrade to `3.5.1` if APT is being used.

Thanks

**Comment by tbroyer** [comment]
I added a comment regarding annotation processors, thanks for the suggestion.

I'll wait for GWT 2.8.2 before cutting a new release though.
