### ISSUE TITLE
What to enter for package on the command line?

### ISSUE THREAD

**Issue by dhoffer** [tbroyer/gwt-maven-archetypes#49]
I'm trying to use this plugin to create a modular-webapp but it asked for what 'package' to use on the command line, I can't find any docs that say what to add here.

It also asks for module-short-name, can't find any docs on that either.

Regarding the 'package' I get that now, I was thinking this was asking about the new custom packaging this plugin uses...I read someplace before I found this plugin...but this just wanted my java package name.

**Comment by tbroyer** [comment]
Wrt `package`, this is the Java package of the generated source files (the folder hierarchy inside `src/main/java`, and the value of the `package` line in the Java files). This is a standard Maven Archetype property.

`module-short-name` will be the `rename-to=""` inside the `.gwt.xml` file, i.e. the name of the output folder and  `.nocache.js` file. This maybe I should document somewhere…
