### ISSUE TITLE
mygwtnew-server cannot be added to tomcat sever ?

### ISSUE THREAD

**Issue by GodIT** [tbroyer/gwt-maven-archetypes#50]
![image](https://user-images.githubusercontent.com/1705460/32696942-b8241606-c7bf-11e7-93d3-9db5b695e5cb.png)

project's properties of mygwtnew-server:
![image](https://user-images.githubusercontent.com/1705460/32696944-d616fc64-c7bf-11e7-9af9-e8aa0e6a8af2.png)

**Comment by tbroyer** [comment]
This looks like an Eclipse issue; please use the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit) to ask for support.
