### ISSUE TITLE
Newly created archetype has build failure

### ISSUE THREAD

**Issue by comzine** [tbroyer/gwt-maven-archetypes#56]
The parameters 'moduleName' for goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-9:compile are missing or invalid.

Commands:
mvn archetype:generate \
                                -DarchetypeGroupId=net.ltgt.gwt.archetypes \
                                -DarchetypeVersion=LATEST \
                                -DarchetypeArtifactId=modular-webapp
mvn gwt:compile

**Comment by tbroyer** [comment]
You're trying to execute `gwt:compile` on all modules of the reactor, including the root module.
What are trying to achieve? Most likely you're actually looking for `mvn package` (or `mvn package -pl *-client -am`)
