### ISSUE TITLE
the project is not compiling 

### ISSUE THREAD

**Issue by transdz** [tbroyer/gwt-maven-archetypes#57]
I generated a project from the maven archetype like you mentionned in your tutorial and when i run 
mvn jetty:run -pl *-server -am
 i get an error :
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.4.8.v20171121:run (default-cli) on project logistique-server: Failure: Address already in use -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :logistique-server

**Comment by tbroyer** [comment]
Either you already ran that command, or you have something else listening on the same port (defaults to 8080).

Have a look at the jetty-maven-plugin documentation for how you can change that default port: https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html

**Comment by transdz** [comment]
How can i specify another port . ??  what is the name of the property .?
-Djetty.http.port=8443 this line make the project run with the command line but i want to add it in  the configuration file

**Comment by tbroyer** [comment]
From the jetty-maven-plugin documentation, apparently something like:

```xml
<plugin>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-maven-plugin</artifactId>
  <configuration>
    <httpConnector>
      <port>8443</port>
    </httpConnector>
  </configuration>
</plugin>
```

**Comment by transdz** [comment]
Thank you very much @tbroyer   :+1:
