### ISSUE TITLE
Is there any sample to using ltgt plugin for GWTP?

### ISSUE THREAD

**Issue by amiriahmad72** [tbroyer/gwt-maven-archetypes#59]
Is there any sample to using `ltgt` plugin for [GWTP](https://github.com/ArcBees/GWTP)?

**Comment by tbroyer** [comment]
Not here, and I don't know of any (and btw GWTP looks like it's no longer actively maintained), but it looks like you could start from the modular-webapp archetype from here and add the GWTP dependency:
```xml
        <dependency>
            <groupId>com.gwtplatform</groupId>
            <artifactId>gwtp-mvp-client</artifactId>
            <version>${gwtp.version}</version>
            <scope>provided</scope>
        </dependency>
```
and then follow on with the "from scratch" steps from the documentation (just replace "create file" with "update file", as most of them will already exist, just not at the exact same path): http://dev.arcbees.com/gwtp/get-started/from-scratch/Create-Files.html
