### ISSUE TITLE
${module.toLowerCase()} isn't replaced but lands somewhere in the source as is

### ISSUE THREAD

**Issue by thomas725** [tbroyer/gwt-maven-archetypes#61]
Hi there!

I just tried the moudlar-webapp archetype and starting dev mode gives me a 404 on 
`http://localhost:8080/$%7Bmodule.toLowerCase()%7D/$%7Bmodule.toLowerCase()%7D.nocache.js`
which seems like ${module.toLowerCase()} was not replaced by "app" since "App" is the default module name I accepted in the wizard.
![image](https://user-images.githubusercontent.com/68635351/90125180-ddbdef80-dd61-11ea-8013-ad87a83cac23.png)

**Comment by thomas725** [comment]
starting over and manually inserting "app" instead of leaving the default in the archetype generation wizard makes it work correctly.

**Comment by tbroyer** [comment]
Thanks for your report but this is actually documented (for years) already: https://github.com/tbroyer/gwt-maven-archetypes#compatibility
