### ISSUE TITLE
Archetype for gwt-lib

### ISSUE THREAD

**Issue by TDesjardins** [tbroyer/gwt-maven-archetypes#65]
Would be useful to have an archetype for creating GWT library projects (packaging `gwt-lib`).

**Comment by tbroyer** [comment]
Do we really need an archetype for such a simple setup? → https://tbroyer.github.io/gwt-maven-plugin/usage.html

Do you have something else in mind?

(the archetypes here are about client/shared/server ; you'll note there's no archetype either for a gwt-app with no server side)

**Comment by TDesjardins** [comment]
> Do you have something else in mind?

Nope, just a simple project setup. How you would create such project? Copy n' paste or by hand?

**Comment by tbroyer** [comment]
That's what I would do personally, yes.

I could accept a PR but what would the archetype contain? only a pom.xml and module.gwt.xml? some Java code? what kind of code then?

What about "Java libraries with a GWT adapter" (think Guava + guava-gwt for example, or dagger + dagger-gwt), should there be an archetype for those too?

(the existing archetypes were quite easy as they simply adapted GWT's `webAppCreator` project to the Maven multi-module layout, and I then derived RequestFactory and Guice/Dagger variants)

**Comment by TDesjardins** [comment]
> That's what I would do personally, yes.

Sounds like the cost-benefit ratio is insufficient from your point. 

> I could accept a PR but what would the archetype contain? only a pom.xml and module.gwt.xml? some Java code? what kind of code then?

Yes, only `pom.xml` and `module.gwt.xml`, no Java code.

> What about "Java libraries with a GWT adapter" (think Guava + guava-gwt for example, or dagger + dagger-gwt), should there be an archetype for those too?

Nope.
