### ISSUE TITLE
update version of GWT to 2.11.0 

### ISSUE THREAD

**Issue by FrankHossfeld** [tbroyer/gwt-maven-archetypes#68]
As mentioned in the discussion: [https://groups.google.com/g/google-web-toolkit/c/hl1H7S280gk, the gettingstarted-v2.html](https://groups.google.com/g/google-web-toolkit/c/hl1H7S280gk, the gettingstarted-v2.html) now uses the `modular-webapp` from this gwt-maven-archetype to generate a Maven project. ATM, the archetype is based on GWT 2.10.0 and Jetty 9.

Updating the GWT version should not be so hard. In this case the server will use the "old" javax-stuff. I tried to update Jetty to version 11. With a frew changes, a runnable project is generated. Only drawback, it requires at least Java 11.

We have now three opportunities:

* Update GWT and stay with Jetty 9
* Update GWT and Jetty (11.x) and now using the jakarta stuff
* add another archetype so that we have both

 What do you think?

**Comment by tbroyer** [comment]
* 2b065bbbb6578175c69a907c662c3ffb4205d8d5 updates GWT to 2.11.0
* eecf349d0d3e772cd8ff3c7eaf6c97364f305760 updates to source level 11 (and drops support for Java 8)
* 7a582529005f6f2fa07e6c713968238b2e622368 migrates the modular-* archetypes to jakarta.servlet and Jetty 11

Not sure what to do with the dagger-guice-rf-activities archetype yet.

**Comment by tbroyer** [comment]
2024.1.24 versions just released, and I deleted the dagger-guice-rf-activities archetype.
