### ISSUE TITLE
Generated POM file has white space lines

### ISSUE THREAD

**Issue by Oberonc** [tbroyer/gwt-maven-archetypes#71]
When I run the command:
```
$ mvn archetype:generate \
>    -DarchetypeGroupId=net.ltgt.gwt.archetypes \
>    -DarchetypeVersion=LATEST \
>    -DarchetypeArtifactId=modular-webapp

```
it runs just fine and generate the expected code, however in the generated content the main pom.xml file (in the root directory, unlike the children directories of client/server/share) has 2 white space lines between every text line.
It is more of an annoyance, since I need to run a white space cleaning command each time.
For example:
```
sed -i '/^[[:space:]]*$/d' pom.xml
```

**Comment by FrankHossfeld** [comment]
AFAIK, this is related to a problem with the maven-archetype-plugin. See: https://issues.apache.org/jira/browse/ARCHETYPE-587

**Comment by tbroyer** [comment]
Yes probably, and this is why I don't update the plugin in the build for 2 years or so as it then breaks integration tests: https://github.com/tbroyer/gwt-maven-archetypes/commit/3fd2a7ab3840dbcd64e8bb45404636f8d58cb953
